name = "firstpl_pickoff"
configurations = [
    { idx = 1, name = "IN", value = 8.0 },
    { idx = 2, name = "OUT", value = 24.9999 },
]
unit = "mm"
offset = 0

[serial]
timeout = 0.5
port = "/dev/serial/by-id/usb-Newport_CONEX-AGP_A60V8WBS-if00-port0"
baudrate = 921600
xonxoff = true
