name = "firstpl_wollaston"
configurations = [
    { idx = 1, name = "IN", value = 5.0 },
    { idx = 2, name = "OUT", value = 24.9999 },
]
unit = "mm"
offset = 0

[serial]
timeout = 0.5
port = "/dev/serial/by-id/usb-Newport_CONEX-AGP_A606QD57-if00-port0"
baudrate = 921600
xonxoff = true
