name = "vampires_camfocus"
configurations = [
    { idx = 1, name = "Dual", value = 13.450252500000001 },
    { idx = 2, name = "Single", value = 4.09470225 },
    { idx = 3, name = "Pupil", value = 22.084903125000004 },
    { idx = 4, name = "Defocus", value = 8.199989125000002 },
    { idx = 5, name = "VPL", value = 12.43 },
]
unit = "mm"
offset = 0

[serial]
timeout = 0.5
port = "/dev/serial/by-id/usb-FTDI_USB_Serial_Converter_FTG4YSH7-if00-port0"
device_number = 3
